language: node_js
sudo: false
cache:
  directories:
    - node_modules
node_js:
  - "6"
branches:
  only:
    - master
    - dev
script:
  - npm test
notifications:
  webhooks:
      urls:
        - https://www.travisbuddy.com/
      on_success: never
      on_failure: always
      on_start: never
      on_cancel: never
      on_error: never
